# Generated by Django 5.0 on 2023-12-24 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('registry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registry_base.registry')),
                ('name', models.CharField(max_length=32)),
            ],
            bases=('registry_base.registry',),
        ),
    ]
