CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE
);

CREATE TABLE session (
  id TEXT NOT NULL PRIMARY KEY,
  users_id INTEGER NOT NULL,
  FOREIGN KEY (users_id) REFERENCES users (id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expired_at TIMESTAMP
);
