CREATE TABLE user {
  ID SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
};

CREATE TABLE user_session (
  id TEXT NUT NULL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  expires_at TIMESTAMP
)
