ALTER TABLE account
ADD COLUMN password TEXT NOT NULL,
ADD COLUMN last_login TIMESTAMP NOT NULL,
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN is_verified BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN is_staff BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN is_admin BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN is_superuser BOOLEAN NOT NULL DEFAULT FALSE;
